### ISSUE TITLE
cross_buildでbinaryが作成できない

### ISSUE THREAD

**Issue by ryoppippi** [tanakh/cargo-atcoder#22]
![スクリーンショット 2020-04-30 14 31 29](https://user-images.githubusercontent.com/1560508/80675409-566ca900-8aef-11ea-8f71-dacca70c2194.png)
OSはmacOS 10.15
Dockerは19.03.8
cargo 1.42.0です
ちなみに`cargo build --release`は問題なく動きました。

**Comment by qryxip** [comment]
#18 で発生したみたいですね。 `cross`で動作を確認するのを忘れていました。 すみません。

https://github.com/tanakh/cargo-atcoder/blob/e51f21fd367586c03f600862d52eb81a8a3da2e8/src/main.rs#L658-L669

`cross`に`--manifest-path <絶対パス>`を渡すとそのままコンテナ内のパスと解釈されてしまうっぽいです。

![cross](https://user-images.githubusercontent.com/14125495/80764916-b0678000-8b7c-11ea-9823-8b18197d1a53.png)
