### ISSUE TITLE
Some command require users to login for even finished contests

### ISSUE THREAD

**Issue by qryxip** [tanakh/cargo-atcoder#31]
現在`new`や`test`等のコマンドは終了後のコンテストに対してもログインを要求します。

例えば`test`時のこれは一旦見て404なら`"Please login first"`で良いはずです。
https://github.com/tanakh/cargo-atcoder/blob/f93acbb42aa446faf14aac08a764e4a70a01e5bf/src/atcoder.rs#L378-L381

不要なログインを要求しないことで #30 のようなテストが追加できます。 repository owner(=tanakhさん)のクレデンシャルを[こんな感じで](https://github.com/qryxip/snowchains/blob/b42598cfbb390354ef5acc7c1ac63a9dcf3e8e16/.github/workflows/ci.yml#L98-L105)使うという方法も無くはないですが。

**Comment by tanakh** [comment]
なるほど、どうせsubmitするならそれらのコマンドがログインを要求しても使い勝手としては変わらないのかなと思っていましたが、テストなどを考えるなら、利便性に繋がりますかね。ありがとうございます。
