### ISSUE TITLE
HTML character references are not converted in test cases

### ISSUE THREAD

**Issue by tyu-ru** [tanakh/cargo-atcoder#33]
[ABC078のA問題](https://atcoder.jp/contests/abc078/tasks/abc078_a)のようにテストケースにHTMLのCharacter Referenceが混ざっている場合に元の文字へ変換されていない不具合があるようです

```
running 3 tests
test sample 1 ... FAILED
test sample 2 ... FAILED
test sample 3 ... ok

---- sample 1 ----
input:
     1 | A B

expected output:
     1 | &lt;

your output:
     1 | <

---- sample 2 ----
input:
     1 | E C

expected output:
     1 | &gt;

your output:
     1 | >

test result: FAILED. 1 passed; 2 failed
```

**Comment by qryxip** [comment]
#34 の[linked issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)になってなかったのでopenのままですがこれcloseすべきでは
