### ISSUE TITLE
`--quiet` is specified for the `gen-binary` command

### ISSUE THREAD

**Issue by qryxip** [tanakh/cargo-atcoder#40]
[Gitter](https://gitter.im/tanakh/cargo-atcoder)にも書きましたが現在`gen_binary_source`内の`cargo build`には`--quiet`が指定されています。

<https://github.com/tanakh/cargo-atcoder/blob/1e66dee54f01b36b7ff27c1c0f1fba688b0f13e9/src/main.rs#L669-L683>

しかしTODO.mdを見ると

https://github.com/tanakh/cargo-atcoder/blob/1e66dee54f01b36b7ff27c1c0f1fba688b0f13e9/TODO.md#L51

とあります。 [`--quiet`の対象は`Building ...`等の進捗メッセージを含みます](https://docs.rs/cargo/0.44.1/src/cargo/core/shell.rs.html#103)。 この`--quiet`は誤って追加されたものではないでしょうか?

**Comment by tanakh** [comment]
そんな気がします。修正ありがとうございます。
